### ISSUE TITLE
No Manifest.mbdb, but Manifest.db

### ISSUE THREAD

**Issue by harmv** [dinosec/iphone-dataprotection#6]
From a fresh iphone backup, I don't seem to be able to extract the key data.

````
$ python iphone-dataprotection/python_scripts/backup_tool.py /Users/<user>/Library/Application\ Support/MobileSync/Backup/72acbdae9845adbe2d5a0*************************
Device Name : ****'s iPhone vi
Display Name : **** iPhone vi
Last Backup Date : 2016-10-14 18:57:41
IMEI : ****************
Serial Number : **************
Product Type : iPhone7,2
Product Version : 10.0.2
iTunes Version : 12.5.1.21
Extract backup to /Users/<user>/Library/Application Support/MobileSync/Backup_extract ? (y/n)
y
Backup is encrypted
Enter backup password : 
****
Traceback (most recent call last):
  File "iphone-dataprotection/python_scripts/backup_tool.py", line 84, in <module>
    main()
  File "iphone-dataprotection/python_scripts/backup_tool.py", line 81, in main
    extract_backup(backup_path, output_path)
  File "iphone-dataprotection/python_scripts/backup_tool.py", line 37, in extract_backup
    mbdb = MBDB(backup_path)
  File "/Users/harmverhagen/Documents/symeon/infra/phone/iphone-dataprotection/python_scripts/backups/backup4.py", line 91, in __init__
    mbdb = file(path + '/Manifest.mbdb', 'rb')
IOError: [Errno 2] No such file or directory: '/Users/<user>/Library/Application Support/MobileSync/Backup/72acbdae9845adb**********************/Manifest.mbdb'
````

It seems there is no Manifest.mbdb, but rather an Manifest.db file ?
```
$ ls /Users/<user>/Library/Application\ Support/MobileSync/Backup/72acbdae9845adbe2d5a08****************/Manifest.*
/Users/<user>/Library/Application Support/MobileSync/Backup/72acbdae9845adbe2d5a08****************/Manifest.db
/Users/<user>/Library/Application Support/MobileSync/Backup/72acbdae9845adbe2d5a08****************/Manifest.plist
```

**Comment by dinosec** [comment]
Please, check closed issue #5.
